# Creating numpy array

In [1]:
#numpy in array
from numpy import *
arr=array([1,2,3,4,5])
print(arr)

#explicitly mentioning the data type
arr1=array([6,7,8,9,10],float)
print(arr1)

#diff ways of creating numpy array
#array()
arr2=([12,23,34,45,56,67])
print(arr2)

#linspace() 
arr3=linspace(1,12,10) #(start ele,end ele,size of array)
print(arr3)

#arange()
arr4=arange(1,12,3) #(start ele,end ele,differenec of initial with next)
print(arr4)

#logspace() log involved
arr5=logspace(1,40,5)
print(arr5)

#zeros() 
#by default will be float
arr6=zeros(5)
print(arr6)
arr6=zeros(5,int) #making it int type
print(arr6)

#ones()
#by default will be float
arr7=ones(5)
print(arr7)
arr7=ones(5,int) #making it int
print(arr7)

[1 2 3 4 5]
[ 6.  7.  8.  9. 10.]
[12, 23, 34, 45, 56, 67]
[ 1.          2.22222222  3.44444444  4.66666667  5.88888889  7.11111111
  8.33333333  9.55555556 10.77777778 12.        ]
[ 1  4  7 10]
[1.00000000e+01 5.62341325e+10 3.16227766e+20 1.77827941e+30
 1.00000000e+40]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]


# array using matrix function

In [2]:
from numpy import *
arr1=array([[1,2,3,4,9,0],[5,6,7,8,1,2]])
arr2=matrix(arr1)
print("array",arr2)

array [[1 2 3 4 9 0]
 [5 6 7 8 1 2]]


# deep copy

In [4]:
from numpy import *
arr1=array([1,2,3,4,45,56])
print("array before deep copy")
print(arr1)
arr2=arr1.copy()
arr1[4]=50
print("array1",arr1)
print("array2",arr2)
print(id(arr1))
print(id(arr2))

array before deep copy
[ 1  2  3  4 45 56]
array1 [ 1  2  3  4 50 56]
array2 [ 1  2  3  4 45 56]
2018960833792
2018960872352


# shallow copy

In [16]:
from numpy import *
arr1=array([1,2,3,4,45,56])
print("array before shallow copy")
print(arr1)
arr2=arr1.view()
arr1[4]=50
print("array1",arr1)
print("array2",arr2)
print(id(arr1))
print(id(arr2))

array before shallow copy
[ 1  2  3  4 45 56]
array1 [ 1  2  3  4 50 56]
array2 [ 1  2  3  4 50 56]
2018961052016
2018704749872


# finding everything using matrix function

In [5]:
from numpy import *
arr1=matrix('1 2 3;4 5 6;7 8 9')
print("array",arr1)
print("diagnol elements",diagonal(arr1))
print("min ele",arr1.min())
print("max ele",arr1.max())

array [[1 2 3]
 [4 5 6]
 [7 8 9]]
diagnol elements [1 5 9]
min ele 1
max ele 9


# operation in array

In [6]:
from numpy import *
arr1=matrix('1 2 3;4 5 6;7 8 9')
arr2=matrix('2 3 4;7 6 4;9 1 6')
print("arr1=",arr1)
print("arr2=",arr2)
print("Sum=",arr1+arr2)
print("Diffenrence=",arr1-arr2)
print("Multiplication=",arr1*arr2)

arr1= [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2= [[2 3 4]
 [7 6 4]
 [9 1 6]]
Sum= [[ 3  5  7]
 [11 11 10]
 [16  9 15]]
Diffenrence= [[-1 -1 -1]
 [-3 -1  2]
 [-2  7  3]]
Multiplication= [[ 43  18  30]
 [ 97  48  72]
 [151  78 114]]


# addition of two arrays

In [7]:
from numpy import *
arr1=array([1,2,3,4,5])
print("array1= ",arr1)
arr2=array([5,6,7,8,9])
print("array2= ",arr2)
print("added array: ",arr1+arr2)

array1=  [1 2 3 4 5]
array2=  [5 6 7 8 9]
added array:  [ 6  8 10 12 14]


# aliasing

In [8]:
from numpy import *
arr1=array([1,2,3,4,45,56])
print("array before aliasing or changing the value")
print(arr1)
arr2=arr1
arr1[4]=50
print("array1",arr1)
print("array2",arr2)
print(id(arr1))
print(id(arr2))

array before aliasing or changing the value
[ 1  2  3  4 45 56]
array1 [ 1  2  3  4 50 56]
array2 [ 1  2  3  4 50 56]
2018960873872
2018960873872


# incrementing a single array

In [9]:
from numpy import *
arr=array([1,2,3,4,5])
print("original array : ",arr)
arr=arr+6
print("incremented array: ",arr)

original array :  [1 2 3 4 5]
incremented array:  [ 7  8  9 10 11]


# array operations and method

In [12]:
from array import *

arr=array('i',[1,2,3,4,5,6])

#printing the array
#method 1
print(arr)

#method 2
for i in arr:
    print(i)
print("\n")
    
#method 3
for i in range(len(arr)):
    print(arr[i])
print("\n")
    
#method 4
for i in range(6):
    print(arr[i],end=" ")
print("\n")

#address and size
print("address and size of array",arr.buffer_info())

#typecode
print("data type",arr.typecode)

#copying
arr1=array(arr.typecode,(i for i in arr))
print("The new copied array is ",arr1)
print("\n")

#can change the new array performing new operators
arr2=array(arr1.typecode,(i+i for i in arr1))
print("The new altered array is ",arr2)
print("\n")

#user input array elements
arr3=array('i',[])
n=int(input("Enter the length of the array : "))
for i in range(0,n):
    inp=int(input("Enter the array element: "))
    arr3.append(inp)
print(arr3)
    
#searching 
#method 1
num=int(input("Enter the array element to be searched: "))
j=0
for i in arr3:
    if i == num:
        print(j)
    j +=1

#method 2 using in build function
num1=int(input("Enter the array element to be searched: "))
print(arr3.index(num1))

array('i', [1, 2, 3, 4, 5, 6])
1
2
3
4
5
6


1
2
3
4
5
6


1 2 3 4 5 6 

address and size of array (2018960840112, 6)
data type i
The new copied array is  array('i', [1, 2, 3, 4, 5, 6])


The new altered array is  array('i', [2, 4, 6, 8, 10, 12])


Enter the length of the array : 3
Enter the array element: 1
Enter the array element: 2
Enter the array element: 3
array('i', [1, 2, 3])
Enter the array element to be searched: 3
2
Enter the array element to be searched: 1
0


# concatenate 2 array

In [13]:
from numpy import *
arr1=array([1,2,3,4,5,6,7,8,9,10])
print("array1 ",arr1)
arr2=array([11,22,33,44,55])
print("array2 ",arr2)
print("concatenated array: ",concatenate([arr1,arr2]))

array1  [ 1  2  3  4  5  6  7  8  9 10]
array2  [11 22 33 44 55]
concatenated array:  [ 1  2  3  4  5  6  7  8  9 10 11 22 33 44 55]


# flathen and reshape function

In [14]:
from numpy import *
arr1=array([[1,2,3,4,9,0],[5,6,7,8,1,2]])
print("original array",arr1)
arr2=arr1.flatten()
print("flattened array",arr2)
arr3=arr2.reshape(3,4)
print("reshaped array",arr3)
arr4=arr2.reshape(3,2,2)
print("reshaped array",arr4)

original array [[1 2 3 4 9 0]
 [5 6 7 8 1 2]]
flattened array [1 2 3 4 9 0 5 6 7 8 1 2]
reshaped array [[1 2 3 4]
 [9 0 5 6]
 [7 8 1 2]]
reshaped array [[[1 2]
  [3 4]]

 [[9 0]
  [5 6]]

 [[7 8]
  [1 2]]]


# matrices

In [15]:
from numpy import *
arr=array([[1,2,3],[4,5,6]])
print("array=",arr)
print("datatype",arr.dtype)
print("dimensions",arr.ndim)
print("order",arr.shape)
print("no of elements",arr.size)

array= [[1 2 3]
 [4 5 6]]
datatype int32
dimensions 2
order (2, 3)
no of elements 6


# trigometry inbuild functions

In [17]:
from numpy import *
arr=array([11,44,33,22,66,55])
print("Array",arr)
print("Sine",sin(arr))
print("Cosine",cos(arr))
print("tan",tan(arr))
print("log",log(arr))
print("sqrt",sqrt(arr))
print("max",max(arr))
print("min",min(arr))
print("Sum",sum(arr))
print("Sort",sort(arr))

Array [11 44 33 22 66 55]
Sine [-0.99999021  0.01770193  0.99991186 -0.00885131 -0.02655115 -0.99975517]
Cosine [ 0.0044257   0.99984331 -0.01327675 -0.99996083 -0.99964746  0.02212676]
tan [-2.25950846e+02  1.77046993e-02 -7.53130148e+01  8.85165604e-03
  2.65605178e-02 -4.51830879e+01]
log [2.39789527 3.78418963 3.49650756 3.09104245 4.18965474 4.00733319]
sqrt [3.31662479 6.63324958 5.74456265 4.69041576 8.1240384  7.41619849]
max 66
min 11
Sum 231
Sort [11 22 33 44 55 66]
